[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/matches"
  to = "/.netlify/functions/matches"
  status = 200

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/lineup"
  to = "/.netlify/functions/lineup"
  status = 200
